import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/modal-provider";
import {
  LiveblocksProvider,
  RoomProvider,
} from "@liveblocks/react/suspense";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        {/* <LiveblocksProvider publicApiKey="pk_dev_blO_wegBR6LqEpNJMYNOqMcJFiHrLKzfpUUrFCNKTE_AYkiA8HFEjFAm_8FnPaZj"> */}
          <ConvexClientProvider>
            <ModalProvider />
            {children}
          </ConvexClientProvider>
        {/* </LiveblocksProvider> */}
      </body>
    </html>
  );
}
